spring:
  application:
    name: i-spring-cloud-eureka-server-1.0.0
server:
  port: 1111
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  file: /data/logs/icloud/${spring.application.name}.log